[project]
name = "mcp-omni-connect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "colorlog>=6.9.0",
    "mcp[cli]>=1.4.1",
    "openai>=1.67.0",
    "python-dotenv>=1.0.1",
    "rich>=13.9.4",
]
